# Brew taps and settings.
tap "caskroom/cask"
tap "homebrew/php"
tap "homebrew/services"
cask_args appdir: '/Applications'

# Brew casks.
cask "bibdesk"
cask "bitcoin-core"
cask "bittorrent"
cask "dbeaver-enterprise"
cask "dropbox"
cask "filezilla"
cask "firefox"
cask "flash-player"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "keka"
cask "libreoffice"
cask "mysqlworkbench"
cask "opera"
cask "postman"
cask "skype"
cask "slack"
cask "staruml"
cask "texmaker"
cask "vlc"
cask "virtualbox"

# Terminal tools.
brew "gource"
brew "nmap"
brew "openssl"
brew "tree"
brew "wget"

# Development environment.
brew "bash"
brew "tmux"
brew "zsh"

# Development tools.
brew "docker"
brew "gcc"
brew "gdb"
brew "git"
brew "cmake"
brew "macvim"
brew "mysql"
brew "node" # Need to run installer first.
brew "php71"
brew "python"
brew "python3"
brew "scala"

# Modules
brew "php71-oauth"
brew "php71-pdo-dblib"
brew "php71-xdebug"
